AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'config/initializers/devise.rb'
    - 'db/schema.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Max: 30
