name: rails

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          bin/bundle install

      - name: Run rubocop
        run: |
          bin/bundle exec rubocop

      - name: Run tests
        run: |
          bin/bundle exec rails db:migrate
          bin/bundle exec rails test

