name: rails

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Build and test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
          bundle exec slim-lint app/views/
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails webpacker:install
          bundle exec rails test
